pull request
Agula2018/weatherCheckApp pull request #2
Opened 2020-03-07 21:07 UTC by Agula2018

2020-03-08 08:06 UTC, neonelect requested changes
Check the comments

2020-03-08 08:06 UTC, neonelect commented on pom.xml
> +		</dependency>
You don't need that

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +    private final String MAIN_URL = "https://airapi.airly.eu/";
Remove that for now

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +public class AirlyController {
Please add @RequestMapping and a domain path

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +    @RequestMapping("v2/installations/")
remove that

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +                                                   Model model) throws JsonParseException {
You don't need model

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +        return installations;
Please return a mocked value like "OK"

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +                                              Model model) throws JsonParseException {
You don't need model

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +        return installations;
Please return mocked value

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +                                                  Model model) throws JsonParseException {
You don't need model

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +        return measurementHistory;
Please return mocked value

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +                                                         Model model) throws JsonParseException {
You don't need model

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +        return measurementHistory;
Please return mocked value

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +                                                       Model model) throws JsonParseException {
You don't need model

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +        return measurementHistory;
Please return mocked value

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Address.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Arguments.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Arguments.java
> +    public String apiKey;
This won't be needed

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Index.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Installations.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Installations.java
> +    private Integer id;
please use long if ID is a number

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/LocatedMeasurement.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/MeasurementHistory.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/SingleMeasurement.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Sponsor.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Sponsor.java
> +    private Integer sponsorId;
Please use long if ID is a number

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Standards.java
> +@Setter
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/model/Value.java
> +@JsonIgnoreProperties
Consider checking if it's really necessary to have all these annotations

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/service/ParsingService.java
> +public interface ParsingService {
Does it makes sense to have a Interface here?

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/web/BeanController.java
> +public class BeanController {
It's configuration not a controller :)

2020-03-08 08:06 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/web/MainController.java
> +public class MainController {
Please remove this class for now

2020-03-08 14:10 UTC, Agula2018 commented on pom.xml
> +		</dependency>
Removed, done :).

2020-03-08 14:10 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +    private final String MAIN_URL = "https://airapi.airly.eu/";
Ok, done.

2020-03-08 15:09 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +public class AirlyController {
ok, done :)

2020-03-08 15:09 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +    @RequestMapping("v2/installations/")
Ok, done.

2020-03-08 15:09 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +                                                   Model model) throws JsonParseException {
ok :)

2020-03-08 15:09 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +        return installations;
ok :)

2020-03-08 15:09 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +                                              Model model) throws JsonParseException {
ok :)

2020-03-08 15:09 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +        return installations;
ok :)

2020-03-08 15:10 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +                                                  Model model) throws JsonParseException {
ok :)

2020-03-08 15:10 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +        return measurementHistory;
ok :)

2020-03-09 06:50 UTC, neonelect requested changes
Please edit .gitignore file to omit the .idea/ and target/ directories

2020-03-09 06:50 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +@RequestMapping("airapi.airly.eu/v2/")
please leave only v2/ prefix

2020-03-09 14:27 UTC, Agula2018 commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +@RequestMapping("airapi.airly.eu/v2/")
What if I have 2 different prefixes? eg. 
@RequestMapping("v2/installations") and 
@RequestMapping("v2/measurement")?
Should I create a new Controller class for eg. @RequestMapping("v2/measurement")?
Thank you for reply :)

2020-03-10 18:47 UTC, neonelect commented on src/main/java/com/agnieszka/piotrowska/weatherCheckApp/controller/AirlyController.java
> +@RequestMapping("airapi.airly.eu/v2/")
Yeah you should then have 2 different domains so two classes: InstallationsController and MeasurementController

2020-03-10 18:48 UTC, neonelect approved these changes

2020-03-10 18:48 UTC, merged